services:
  db:
    container_name: web-study-project
    image: postgres
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: Nt@2022#
  redis:
    image: redis
    ports:
      - '6379:6379'
    restart: always
